### ISSUE TITLE
Failed to read csv file

### ISSUE THREAD

**Issue by lee-zhg** [IBM/pixiedust-facebook-analysis#38]
When executing the generated code to read CSV file, it failed.

The code are
=========

# insert pandas DataFrame
import sys
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_c0fe4b0610144a049d60e22 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='<key>',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_c0fe4b0610144a049d60e22.get_object(Bucket='leee5ac7151a0774a31aae95eada44af3e0',Key='example_facebook_data.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_2 = pd.read_csv(body)
df_data_2.head()

The error messages are
================
ParserError                               Traceback (most recent call last)
<ipython-input-13-02c9008508d8> in <module>()
     21 if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )
     22 
---> 23 df_data_2 = pd.read_csv(body)
     24 df_data_2.head()
     25 

/usr/local/src/conda3_runtime/home/envs/DSX-Python35-Spark/lib/python3.5/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, skip_footer, doublequote, delim_whitespace, as_recarray, compact_ints, use_unsigned, low_memory, buffer_lines, memory_map, float_precision)
    703                     skip_blank_lines=skip_blank_lines)
    704 
--> 705         return _read(filepath_or_buffer, kwds)
    706 
    707     parser_f.__name__ = name

/usr/local/src/conda3_runtime/home/envs/DSX-Python35-Spark/lib/python3.5/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    449 
    450     try:
--> 451         data = parser.read(nrows)
    452     finally:
    453         parser.close()

/usr/local/src/conda3_runtime/home/envs/DSX-Python35-Spark/lib/python3.5/site-packages/pandas/io/parsers.py in read(self, nrows)
   1063                 raise ValueError('skipfooter not supported for iteration')
   1064 
-> 1065         ret = self._engine.read(nrows)
   1066 
   1067         if self.options.get('as_recarray'):

/usr/local/src/conda3_runtime/home/envs/DSX-Python35-Spark/lib/python3.5/site-packages/pandas/io/parsers.py in read(self, nrows)
   1826     def read(self, nrows=None):
   1827         try:
-> 1828             data = self._reader.read(nrows)
   1829         except StopIteration:
   1830             if self._first_chunk:

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.read()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 36, saw 2

**Comment by scottdangelo** [comment]
@lee-zhg Did you find a workaround?
We are seeing issues with encodings, i.e. we had to fix our own CSV file with:
`df_data_1 = pd.read_csv(body, encoding='latin-1')`
