### ISSUE TITLE
Ethics?

### ISSUE THREAD

**Issue by flatsiedatsie** [IBM/pixiedust-facebook-analysis#47]
Does this tool allow one to analyse and understand things that can be traced back to individual Facebook user?

**Comment by stevemart** [comment]
Hey @flatsiedatsie, the notebook uses data that is exported from [Facebook's Analytics](https://analytics.facebook.com/) online tool. The data exported from FB Analytics does not include personally identifiable data. See https://developers.facebook.com/docs/analytics/properties 

> User IDs and user properties can't include any personally identifying information, such as people's names or email addresses.

**Comment by stevemart** [comment]
Further... i'm fairly certain you have to be an admin or a group to look up analytics about the group and the users interacting with the group.
