### ISSUE TITLE
Change Tone Analyzer and NLU authentication to iam_apikey instead of username/password

### ISSUE THREAD

**Issue by lidderupk** [IBM/pixiedust-facebook-analysis#53]
The Tone Analyzer and the NLU services now use the api_key as per the API reference doc. I am creating a PR. Thank you for the great notebook !

**Comment by lidderupk** [comment]
Please see PR https://github.com/IBM/pixiedust-facebook-analysis/pull/54

**Comment by markstur** [comment]
closed with pre #54 
thanks!
